services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: jovyan
      POSTGRES_PASSWORD: jovyan
      POSTGRES_DB: service_s3
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jovyan"]
      interval: 5s
      retries: 5

  airflow-db:
    image: postgres:16
    container_name: airflow-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "15433:5432"
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 5

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS: "True"

      AIRFLOW_CONN_PG_CONNECTION: postgresql+psycopg2://jovyan:jovyan@postgres:5432/service_s3
      AIRFLOW_CONN_MINIO_S3: aws://minioadmin:minioadmin@minio:9000

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - chroma_data:/opt/chroma

    ports:
      - "8080:8080"

    depends_on:
      airflow-db:
        condition: service_healthy
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy

    command: airflow standalone

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      retries: 5

  streamlit:
    build: ./streamlit
    container_name: streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/app
      - chroma_data:/opt/chroma
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy

volumes:
  postgres_data:
  airflow_db_data:
  logs:
  plugins:
  minio_data:
  chroma_data: