FROM apache/airflow:3.1.3-python3.11

USER airflow

RUN pip install --no-cache-dir \
    pypdf==4.2.0 \
    python-docx==1.1.2 \
    chromadb==0.5.5 \
    sentence-transformers==3.0.1

USER root

RUN mkdir -p /opt/chroma \
 && chown -R airflow:root /opt/chroma \
 && chmod -R 775 /opt/chroma

USER airflow